title: glikovsky公式ウェブサイト
locale: ja_JP
date_locale: ja
future: true

collections:
  concerts:
    output: true
  history:


defaults:
  - scope:
      path: ""
      type: "concerts"
    values:
      layout: "concert"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      categories: "blog"
  - scope:
      path: ""
    values:
      layout: "default"

permalink: /:categories/:year-:month-:day/:title

plugins:
  - jekyll-date-localization
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap