title: glikovsky公式ウェブサイト
locale: ja_JP

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      categories: "blog"
  - scope:
      path: ""
    values:
      layout: "default"

permalink: /:categories/:year-:month-:day/:title

plugins:
  - jekyll-date-localization
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap